# Generated by Django 6.0.4 on 2026-04-27 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='has_unlocked_daily_challenge',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='level_5_completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
