# Generated by Django 6.0.4 on 2026-04-27 08:31

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daily', '0001_initial'),
        ('questions', '0002_alter_question_ai_generated'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailychallenge',
            name='theme',
        ),
        migrations.RemoveField(
            model_name='dailychallenge',
            name='questions',
        ),
        migrations.RemoveField(
            model_name='dailychallengeattempt',
            name='xp_earned',
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='title',
            field=models.CharField(default='Daily Master Challenge', max_length=200),
        ),
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='correct_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='time_taken_seconds',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='total_questions',
            field=models.IntegerField(default=15),
        ),
        migrations.AddField(
            model_name='dailychallengeattempt',
            name='wrong_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='dailychallenge',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='dailychallengeattempt',
            name='completed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='dailychallengeattempt',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='DailyChallengeQuestion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('order', models.PositiveIntegerField()),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='challenge_questions', to='daily.dailychallenge')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'db_table': 'daily_challenge_questions',
                'ordering': ['order'],
                'unique_together': {('challenge', 'question')},
            },
        ),
        migrations.AddField(
            model_name='dailychallenge',
            name='questions',
            field=models.ManyToManyField(through='daily.DailyChallengeQuestion', to='questions.question'),
        ),
        migrations.CreateModel(
            name='DailyChallengeAnswer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('selected_index', models.IntegerField()),
                ('is_correct', models.BooleanField()),
                ('time_taken_seconds', models.IntegerField(blank=True, null=True)),
                ('answered_at', models.DateTimeField(auto_now_add=True)),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='daily.dailychallengeattempt')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
            ],
            options={
                'db_table': 'daily_challenge_answers',
                'unique_together': {('attempt', 'question')},
            },
        ),
    ]
