# Generated by Django 6.0.4 on 2026-04-26 20:08

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('difficulty_level', models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)])),
                ('total_questions', models.IntegerField(default=10)),
                ('correct_answers', models.IntegerField(default=0)),
                ('xp_earned', models.IntegerField(default=0)),
                ('time_taken_seconds', models.IntegerField(null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'game_sessions',
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='SessionQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('selected_index', models.IntegerField(null=True)),
                ('is_correct', models.BooleanField(null=True)),
                ('time_taken_seconds', models.IntegerField(null=True)),
                ('answered_at', models.DateTimeField(blank=True, null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='game.gamesession')),
            ],
            options={
                'db_table': 'session_questions',
                'ordering': ['order'],
                'unique_together': {('session', 'question')},
            },
        ),
        migrations.AddField(
            model_name='gamesession',
            name='questions',
            field=models.ManyToManyField(through='game.SessionQuestion', to='questions.question'),
        ),
        migrations.CreateModel(
            name='UserQuestionHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('times_seen', models.IntegerField(default=1)),
                ('times_correct', models.IntegerField(default=0)),
                ('last_seen_at', models.DateTimeField(auto_now=True)),
                ('first_seen_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_question_history',
                'indexes': [models.Index(fields=['user', 'question'], name='user_questi_user_id_6851db_idx')],
                'unique_together': {('user', 'question')},
            },
        ),
    ]
