# Generated by Django 6.0.4 on 2026-04-26 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='current_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='difficulty_level',
            field=models.IntegerField(choices=[(1, 1), (2, 2), (3, 3), (4, 4), (5, 5)], default=1),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('failed', 'Failed'), ('completed', 'Completed'), ('abandoned', 'Abandoned')], default='active', max_length=20),
        ),
    ]
