# Generated by Django 6.0.4 on 2026-04-26 20:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Leaderboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('alltime', 'All Time')], db_index=True, max_length=10)),
                ('rank', models.IntegerField()),
                ('xp', models.IntegerField()),
                ('correct_answers', models.IntegerField(default=0)),
                ('sessions_played', models.IntegerField(default=0)),
                ('computed_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaderboard_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'leaderboard',
                'ordering': ['period', 'rank'],
                'unique_together': {('period', 'user')},
            },
        ),
    ]
