# Generated by Django 6.0.4 on 2026-04-26 20:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('law', 'Law (Torah/Pentateuch)'), ('history', 'History'), ('poetry', 'Poetry & Wisdom'), ('prophecy', 'Prophecy'), ('gospel', 'Gospel'), ('epistle', 'Epistle'), ('apocalyptic', 'Apocalyptic')], max_length=50, unique=True)),
                ('display_name', models.CharField(max_length=100)),
                ('icon', models.CharField(default='book', max_length=50)),
            ],
            options={
                'verbose_name_plural': 'categories',
                'db_table': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('question_text', models.TextField()),
                ('options', models.JSONField()),
                ('correct_index', models.IntegerField()),
                ('explanation', models.TextField()),
                ('bible_reference', models.CharField(max_length=100)),
                ('full_verse_text', models.TextField(blank=True)),
                ('difficulty', models.IntegerField(choices=[(1, 'Easy'), (2, 'Normal'), (3, 'Medium'), (4, 'Hard'), (5, 'Master')], db_index=True)),
                ('testament', models.CharField(choices=[('old', 'Old Testament'), ('new', 'New Testament'), ('both', 'Both Testaments')], db_index=True, max_length=10)),
                ('cognitive_type', models.CharField(choices=[('recall', 'Recall'), ('comprehension', 'Comprehension'), ('application', 'Application'), ('analysis', 'Analysis'), ('synthesis', 'Synthesis')], db_index=True, max_length=20)),
                ('topic_tags', models.JSONField(default=list)),
                ('book_name', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='pending', max_length=20)),
                ('quality_score', models.FloatField(default=0.0)),
                ('ai_generated', models.BooleanField(default=True)),
                ('generation_model', models.CharField(blank=True, max_length=50)),
                ('reviewer_notes', models.TextField(blank=True)),
                ('times_served', models.IntegerField(default=0)),
                ('times_correct', models.IntegerField(default=0)),
                ('times_incorrect', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='questions.category')),
            ],
            options={
                'db_table': 'questions',
                'indexes': [models.Index(fields=['difficulty', 'status'], name='questions_difficu_646aef_idx'), models.Index(fields=['difficulty', 'testament', 'status'], name='questions_difficu_3a24a3_idx'), models.Index(fields=['difficulty', 'category', 'status'], name='questions_difficu_e8d60c_idx')],
            },
        ),
    ]
