# Generated by Django 6.0.4 on 2026-04-26 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='ai_generated',
            field=models.BooleanField(default=False),
        ),
    ]
